### ISSUE TITLE
object id from TiledObject is dropped when parsing

### ISSUE THREAD

**Issue by Hwan-seok** [AlexHeyman/TiledReader#12]
There is no id property to TiledObject so we cannot use it somewhere.

**Comment by AlexHeyman** [comment]
Is the `getID()` method of the `TiledObject` class not working as intended?

**Comment by AlexHeyman** [comment]
It occurs to me that `TiledObject.getID()` isn't in the most recent official release of TiledReader; it's just been added to the GitHub version since then. If you're not using the GitHub version of TiledReader, try switching to it and see if that fixes your problem.

**Comment by Hwan-seok** [comment]
Oh, I didn't know that.

I downloaded the it from maven repository as a dependencies which doesn't have it.
Would you mind releasing it to the repository to easily add this to our own project?
There are some users that are unfamiliar with the java environment.

BTW, thanks for the great project!
