### ISSUE TITLE
Add support for default values for properties from objecttypes.xml

### ISSUE THREAD

**Issue by jvisser** [AlexHeyman/TiledReader#6]
Object types contain the default values for properties. When the default property value is used for the tile it is not specified in the tileset file (only the type of the tyle). So in order to determine the default values of the tile properties objecttypes.xml must be read.

It would be nice if TiledReader would automatically merge with the default values from objecttypes for the tile type. This would eliminate needing to manually parse objecttypes.xml by users of the TiledReader library.

**Comment by AlexHeyman** [comment]
I haven't heard of objecttypes.xml before. Where is it located? Does the Tiled documentation mention it anywhere?

**Comment by jvisser** [comment]
I can't seem to find documentation on the storage format actually. But functionally it's documented here: 
- https://doc.mapeditor.org/en/stable/manual/custom-properties/#typed-tiles. 
- https://doc.mapeditor.org/en/stable/manual/projects/#what-s-in-a-project

**Comment by jvisser** [comment]
Also just saw this issue on the tiled repo which is someone basically having the same problem as I have. https://github.com/bjorn/tiled/issues/2872.

PS: I updated my original post to indicate better what I would expect TiledReader to do with objecttypes.xml.

**Comment by AlexHeyman** [comment]
This situation looks tricky. I'm not clear on how a parser is even supposed to find the appropriate object types file based on the information in a TMX or TSX file. To support this, would we need to extend TiledReader to read project files too?

As refox1 said, this feature seems badly designed. Besides, isn't implementing "object types" what template files are for?

**Comment by jvisser** [comment]
Object types are more generic types. In the future it will be used for all objects (maps/tilesets also). In my map design using meta tiles I heavily depend on that feature for typed tiles. I don't even use the object layer atm.

A simple solution would be to allow the user of TiledReader to just read object types as separate object. And configure the map reader to use the object types object. At this time getMap() is a static method. Maybe make the TiledReader class an instantiable class that can be configured to use an object types file. It is then up to the user to specify the file.

Then when properties are read merge them with the default properties.

**Comment by AlexHeyman** [comment]
> Maybe make the TiledReader class an instantiable class that can be configured to use an object types file. It is then up to the user to specify the file.

This sounds sensible - and as it happens, there's already another proposed change to TiledReader that involves making the `TiledReader` class instantiable. I should have time to add object types support in this form sometime soon.

**Comment by jvisser** [comment]
Cool!

**Comment by AlexHeyman** [comment]
I've added the object types support. Let me know if everything works for your purposes.

**Comment by jvisser** [comment]
Hi, I tested it. But got this error when reading objecttypes.xml. 
`Exception in thread "main" java.lang.RuntimeException: javax.xml.stream.XMLStreamException: (line 4, column 48): Missing required tag attribute (default)
	at org.tiledreader.TiledReader.readObjectTypes(TiledReader.java:562)`

Not all properties in my objecttypes.xml specify a default value. I think that may be the problem.

**Comment by AlexHeyman** [comment]
I see. I've changed the parser so any object type property that doesn't specify a default value gets the standard default value for properties of that type (e.g. "" for a string).

**Comment by jvisser** [comment]
That part works. But I'm still not seeing the properties with default value on the tiles. I think that this maybe only works for the object layer now (which I don't use)?

**Comment by AlexHeyman** [comment]
Sorry about that. I didn't read the Tiled documentation on the subject closely enough to realize that the tiles themselves also need to inherit the custom properties from their types.

I've made another change that hopefully actually got property inheritance working the way Tiled does it, for both objects and tiles. Does it work as expected for you now?

**Comment by jvisser** [comment]
It works now! Thanks!

**Comment by AlexHeyman** [comment]
Excellent. I'll close the issue now.
